### ISSUE TITLE
Inquiry about mesh extraction

### ISSUE THREAD

**Issue by TLB-MISS** [YangLing0818/SemanticSDS-3D#2]
Thank you so much for providing the code for this nice work!
How do I extract mesh from trained models?

Thanks

**Comment by aiihn** [comment]
Thank you for your interest in our work!

To export the mesh, please refer to the [README of GSGEN](https://github.com/gsgen3d/gsgen?tab=readme-ov-file#exports) and try using the `utils/export.py` script to extract the mesh. Since we haven't focused on extracting mesh previously, you might encounter issues using it directly. If so, you can compare the differences between [utils/paper.py in our GitHub repository](https://github.com/YangLing0818/SemanticSDS-3D/blob/1c0ea01f699efbb922c4c33af148932c7d80abac/utils/paper.py) and [utils/paper.py in the GSGEN GitHub repository](https://github.com/gsgen3d/gsgen/blob/e60994e557b685d5df57ec0bb48460782091ec4d/utils/paper.py). Based on these differences, you can make similar modifications and adaptations to `utils/export.py`.

Thanks!
